rev/views/home.py
import math
from flask import Blueprint, render_template, flash, redirect, url_for, abort, request
from rev.models import Checking, Breaks, Reports
from rev.helpers import current_date, current_datetime, calc_datetime
from rev.forms import FormCheckout, FormReport
from rev.users import secure, current_user
from peewee import PeeweeException

bp = Blueprint('home', __name__)


@bp.before_request
def secure_site():
    return secure()


def _get_404(model, **exp):
    try:
        return model.get(**exp)
    except PeeweeException:
        abort(404)


def _break_choices():
    return ['lunch', 'bio', 'coaching', 'short', 'meeting']


@bp.route('/')
def action_index():
    uid = current_user().id
    current_status = 'out'
    break_choices = _break_choices()
    checking = Checking.select().where(Checking.users == uid, Checking.status == 'in').order_by(Checking.id.desc())
    status_in = Checking.select().where(Checking.users == uid, Checking.status == 'in')

    if status_in.exists():
        current_status = 'in'

    ctx = {
        'checking': checking,
        'current_status': current_status,
        'status': status_in,
        'break_choices': break_choices,
    }
    return render_template('home/index.html', **ctx)
    

@bp.route('/check-in')
def action_check_in():
    uid = current_user().id
    check_record = Checking.select().where(Checking.users == uid).order_by(Checking.id.desc()).limit(1)
    
    checking = Checking(
        users=uid,
        checkin=current_datetime(),
        checkout=current_datetime(),
        status='in',
        total_hours=0,
    )

    if check_record.exists():
        check_record = check_record.get()

        if check_record.status == 'in':
            flash('Cannot <b>CHECK-IN</b>, you are currently in <b>CHECK-IN</b> status', 'danger')

        else:
            try:
                checking.save()
                flash('<b>CHECK-IN</b> successful!', 'success')
            
            except Exception as err:
                flash(f'Failed to add record, Please contact admin. {err}', 'danger')

    else:
        try:
            checking.save()
            flash('<b>Initial CHECK-IN</b> successful!', 'success')
        
        except Exception as err:
            flash(f'Failed to add record, Please contact admin. {err}', 'danger')
    
    # always return to home
    return redirect(url_for('home.action_index'))


@bp.route('/check-out/<int:id>', methods=['GET', 'POST'])
def action_check_out(id):
    uid = current_user().id
    checking = _get_404(Checking, id=id, users=uid)

    form = FormCheckout()

    # check if there are active breaks
    active_breaks = Breaks.select().where(Breaks.users == uid, Breaks.status=='start')
    if active_breaks.exists():
        flash('You have active break, please stop to continue checking out', 'danger')
        return redirect(url_for('home.action_index'))

    if form.validate_on_submit():
        
        if checking.status == 'out':
            flash('This timelog was already Checked-OUT', 'danger')

        else:
            # time difference
            checkout_time = current_datetime()
            total_hours = calc_datetime(checking.checkin, checkout_time)

            checking.checkout = current_datetime()
            checking.status = 'out'
            checking.eod = form.eod.data
            checking.total_hours = total_hours
            checking.updated = current_datetime()
            
            try:
                checking.save()
                flash('CHECK OUT successful!', 'success')
                return redirect(url_for('home.action_index'))
            except Exception as err:
                flash('Failed CHECK-OUT, Please contact admin. {}'.format(err), 'danger')

    return render_template('home/out.html', form=form, checking=checking)
    

@bp.route('/break-start/<string:mode>')
def action_break_start(mode):
    uid = current_user().id
    break_types = _break_choices()
    if mode not in break_types:
        abort(404)

    checkin = Checking.select().where(Checking.status == 'in', Checking.users == uid)\
            .order_by(Checking.id.desc()).limit(1)
    
    if checkin.exists():
        checkin = checkin.get()
        # check if there are active breaks
        break_start = Breaks.select().where(Breaks.status == 'start', Breaks.users == uid).limit(1)
        
        if break_start.exists():
            flash('You are currently on break', 'danger')

        else:
            try:
                new_break = Breaks(
                    users=uid,
                    checking=checkin.id,
                    start=current_datetime(),
                    end=current_datetime(),
                    status='start',
                    total_hours=0,
                    mode=mode,
                    )
                new_break.save()
                flash('Break started successfully', 'success')

            except Exception as err:
                flash(f'Error processing [{err}]', 'danger')
    
    else:
        flash('You are not Checked-IN', 'danger')

    return redirect(url_for('home.action_index'))


@bp.route('/break-stop/<int:id>')
def action_break_stop(id):
    uid = current_user().id
    breaks = _get_404(Breaks, id=id, users=uid)

    if breaks.status == 'stop':
        abort(404)

    try:
        end_time = current_datetime()
        calc_hours = calc_datetime(breaks.start, end_time)
        breaks.status = 'stop'
        breaks.end = end_time
        breaks.total_hours = calc_hours
        breaks.save()
        flash('Break has stopped', 'success')

    except PeeweeException as err:
        flash('Something went wrong', 'danger')

    return redirect(url_for('home.action_index'))


@bp.route('/checking-details/<int:id>')
def action_checking_details(id):
    uid = current_user().id
    checking = _get_404(Checking, id=id)

    total_log_hours = checking.total_hours
    total_break_hours = 0

    for item in checking.breaks:
        total_break_hours += item.total_hours

    working_hours = total_log_hours - total_break_hours
    from_url = request.args.get('from_url') or url_for('home.action_timelogs')

    return render_template(
        'home/checking-details.html', 
        checking=checking, 
        current_date=current_date(),
        working_hours=working_hours,
        total_break_hours=total_break_hours,
        from_url=from_url,
    )


@bp.route('/timelogs')
def action_timelogs():
    uid = current_user().id
    page = int( request.args.get('page') or 1)
    timelogs_count = Checking.select().where(Checking.users == uid).count()
    timelogs = Checking.select().where(Checking.users == uid).order_by(Checking.created.desc()).paginate(page,10)
    page_number = math.ceil( (timelogs_count or 1) / 10 ) + 1

    return render_template('home/timelogs.html', 
                           timelogs=timelogs, page=page, 
                           page_number=page_number, 
                           timelogs_count=timelogs_count,
                        )


@bp.route('/report', methods=['GET', 'POST'])
def action_report():
    form = FormReport()
    msg = None

    form.resolved.data = False

    if request.method == 'POST':
        try:
            Reports.create(
                title=form.title.data,
                severity=form.severity.data,
                details=form.details.data,
                resolved=form.resolved.data,
                users=current_user().id,
                )
            flash('Report was submitted', 'success')
            return redirect(url_for('home.action_report'))
        except Exception as err:
            flash(f'Something went wrong. error{err}', 'danger')
        
    return render_template('home/report.html', form=form)

rev/templates/home/checking-details.html
{% extends 'layout/main.html' %}


{% block content %}

    <div class="container py-5">
        <div class="row">
            <div class="col">
                <h4 class="mt-3">Timesheet Details</h4>
                <div class="py-3">
                    <div class="p-3 border rounded">
                        <div class="row g-3">
                            <div class="col">
                                <div class="p-3 rounded bg-info bg-opacity-10">
                                    <em>Working Time</em>
                                    <p class="lead fw-bold">{{working_hours|round(2)}} hrs</p>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-3 rounded bg-info bg-opacity-10">
                                    <em>Total Break Time</em>
                                    <p class="lead fw-bold">{{total_break_hours|round(2)}} hrs</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="p-3 border mt-3 rounded">
                        <h5>Timelog</h5>
                        
                        <div class="row mt-2 g-3">
                            <div class="col">
                                <div class="p-3 rounded bg-primary bg-opacity-10">
                                    <em>Check-IN</em>
                                    <p class="lead fw-bold">{{checking.checkin}}</p>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-3 rounded bg-primary bg-opacity-10">
                                    <em>Check-OUT</em>
                                    <p class="lead fw-bold">{{checking.checkout}}</p>
                                </div>
                            </div>
                            <div class="col">
                                <div class="p-3 rounded bg-primary bg-opacity-10">
                                    <em>Hours</em>
                                    <p class="lead fw-bold">{{checking.total_hours}}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="p-3 border rounded mt-3">
                        <h5>Breaks</h5>
                        {% if checking.breaks %}
                         <table class="table">
                            <thead>
                                <th>Mode/Type</th>
                                <th>Start</th>
                                <th>End</th>
                                <th>Total Hours</th>
                            </thead>
                            <tbody class="table-group-divider">
                                {% for item in checking.breaks %}
                                <tr>
                                    <td>{{item.mode}}</td>
                                    <td>{{item.start}}</td>
                                    <td>{{item.end}}</td>
                                    <td>{{item.total_hours}} hrs</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% else %}
                            <em>No Records Found</em>
                        {% endif %}
                    </div>

                    <div class="p-3 border rounded mt-3">
                        <h5>End of Day Report</h5>
                        <div class="pb-3" style="white-space: pre-line;">
                            {{- checking.eod -}}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock content %}

rev/templates/home/index.html
{% extends 'layout/main.html' %}


{% block content %}

    <div class="container py-5">
        <div class="row">
            <div class="col">
                <div class="p-4 shadow-sm border rounded-10">
                    <div class="row g-3 d-flex align-items-center">
                        <div class="col-6">
                            <h3>Hi {{current_user.first_name}}</h3>
                        </div>
                        <div class="col-6 text-end">
                            {% if current_status == 'out' %}
                                <a href="{{url_for('home.action_check_in')}}" class="btn btn-primary" up-follow>
                                    Check IN
                                </a>
                            {% endif %}
                            
                            {% if current_status == 'in' %}
                                You are <span class="text-success fw-bold">checked-IN</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% if current_status == 'in' %}
            
            <div class="row mt-3">
                <div class="col">
                    <div class="p-3 border rounded-10 shadow-sm">
                        <h6>Select breaks</h6>
                        {% for break in break_choices %}
                            <a href="{{url_for('home.action_break_start', mode=break)}}" class="btn btn-sm btn-outline-primary" up-follow>
                                {{break}}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>

        {% endif %}

        <div class="row mt-3">
            <div class="col">
                <div class="">
                    {% for item in checking %}
                        <div class="rounded-10 shadow-sm border {{'border-primary' if item.status=='in' else ''}}">
                            <div class="px-3 py-3">
                                <div class="row g-3 d-flex align-items-center checkin-record">
                                    <div class="col">
                                        <small class="text-muted">IN</small><br/>
                                        <p class="fw-bold" id="checkin-datetime">{{item.checkin}}</p>
                                    </div>
                                    <div class="col">
                                        <small class="text-muted">OUT</small><br/>
                                        {% if item.status == 'in' %}
                                            <p class="fw-bold text-success">in progress</p>
                                        {% else %}
                                            <p class="fw-bold">{{item.checkout}}</p>
                                        {% endif %}
                                    </div>
                                    <div class="col">
                                        {% if item.status == 'in' %}
                                            <small class="text-muted">Time Elapsed</small><br/>
                                            <p class="fw-bold text-primary time-elapsed">--:--</p>
                                        {% else %}
                                            <small class="text-muted">Hours</small><br/>
                                            <p class="fw-bold">{{item.total_hours}}</p>
                                        {% endif %}
                                    </div>
                                    <div class="col text-end">
                                        {% if item.status == 'out' %}
                                            <a href="{{url_for('home.action_checking_details', id=item.id)}}" class="btn btn-light border">
                                                Details
                                            </a>
                                        {% endif %}
                                        {% if item.status == 'in' %}
                                            <a href="{{url_for('home.action_check_out', id=item.id)}}" class="btn btn-danger">
                                                Check-OUT
                                            </a>
                                        {% endif %}
                                    </div>
                                </div>

                                {% if item.breaks %}
                                    
                                    <div class="row pt-2 checkin-break-record">
                                        <div class="col">
                                            <div class="p-3 rounded-10 border bg-light">
                                                <p>BREAKS</p>
                                                <table class="table table-sm">
                                                    <thead>
                                                        <tr>
                                                            <th>Mode</th>
                                                            <th>Start</th>
                                                            <th>End</th>
                                                            <th>Hours</th>
                                                            <th>Status</th>
                                                            <th></th>
                                                        </tr>
                                                    </thead>
                                                    <tbody class="table-group-divider">
                                                        {% for break in item.breaks %}
                                                            <tr>
                                                                <td>{{break.mode}}</td>
                                                                <td> 
                                                                    {% if break.status == 'start' %}
                                                                        <span id="break-time-start">{{break.start}}</span>
                                                                    {% else %}
                                                                        {{break.start}}
                                                                    {% endif %}
                                                                </td>
                                                                <td>
                                                                    {% if break.status == 'start' %}
                                                                        <span class="text-info bk-time-elapsed">in progress</span>
                                                                    {% else %}
                                                                         {{break.end}}
                                                                    {% endif %}
                                                                </td>
                                                                <td>{{break.total_hours}}</td>
                                                                <td>{{break.status}}</td>
                                                                <td>
                                                                    {% if break.status == 'start' %}
                                                                        <a href="{{url_for('home.action_break_stop', id=break.id)}}"
                                                                            class="btn btn-sm btn-outline-danger py-0">
                                                                            Stop    
                                                                        </a>
                                                                    {% endif %}
                                                                </td>
                                                            </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                    {% endfor %}

                    
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

rev/templates/home/out.html
{% extends 'layout/main.html' %}


{% block content %}

    <div class="container py-5">
        <div class="row">
            <div class="col-sm-6">
                <a class="btn btn-secondary" href="{{url_for('home.action_index')}}">&leftarrow; back to home</a><br/><br/>
                <h4>Check-Out</h4>


                <div class="py-3">
                    <div class="p-4 border rounded-10 shadow">
                    <p>
                        Checked-IN at: <span class="fw-bold">{{checking.checkin}}</span>
                    </p>
                    <form method="post" role="form">
                        {{form.hidden_tag()}}
                        <div class="pb-3">
                            {{form.eod.label}}<br/>
                            {{form.eod(class='form-control', style='min-height:150px;')}}
                            <span class="text-danger">{{form.eod.errors[0]}}</span>
                        </div>
                        <div>
                            <button type="submit" class="btn btn-primary">Check OUT</button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

rev/templates/home/report.html
{% extends 'layout/main.html' %}


{% block content %}

<div class="container py-5">
    <div class="row">
        <div class="col">
            <h3>Report <span class="fs-6">(Incident Report)</span></h3>
        </div>
    </div>
    <div class="row">
        <div class="col">
           <div class="p-4 border rounded bg-dark bg-opacity-10">
                <form method="post" up-submit up-disable>
                    <div class="row g-3">
                        {{form.hidden_tag()}}
                        <div class="col-12">
                            {{form.title.label}}
                            {{form.title(class='form-control')}}
                            <small class="text-danger">{{form.title.errors[0]}}</small>
                        </div>
                        <div class="col-12">
                            {{form.severity.label}}
                            {{form.severity(class='form-control')}}
                            <small class="text-danger">{{form.severity.errors[0]}}</small>
                        </div>
                        <div class="col-12">
                            {{form.details.label}}
                            {{form.details(class='form-control', style='min-height:250px;')}}
                            <small class="text-danger">{{form.details.errors[0]}}</small>
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Submit report</button>
                        </div>
                    </div>
                </form>
           </div>
        </div>
    </div>
</div>

{% endblock %}

rev/templates/home/timelogs.html
{% extends 'layout/main.html' %}


{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col">
            <h3>Timelogs</h3>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% if timelogs %}
                <div class="table-responsive">

                    <table class="table table-hover">
                        <thead>
                            <th>IN</th>
                            <th>OUT</th>
                            <th>Total Hrs</th>
                            <th></th>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for item in timelogs %}
                                <tr>
                                    <td>{{item.checkin}}</td>
                                    <td>{{item.checkout}}</td>
                                    <td>{{item.total_hours}}</td>
                                    <td class="text-end">
                                        <a href="{{url_for('home.action_checking_details', id=item.id)}}" 
                                            class="btn btn-sm btn-light border py-0"
                                            up-layer="new" up-size="large">
                                            see details
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                        <caption>
                            Total items: {{timelogs_count}}
                        </caption>
                    </table>

                    <nav aria-label="page navigation">
                        <ul class="pagination">
                            {% for i in range(1, page_number) %}
                                {% if page == i %}
                                    {% set is_active = 'active' %}
                                {% endif %}
                                <li class="page-item">
                                    <a class="page-link {{is_active}}" href="?page={{i}}" up-follow>{{i}}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </nav>
                
                </div>
            {% else %}
                <p class="lead">No results</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}